### ISSUE TITLE
'gameboy-emulator' executable is being created in the wrong path and without proper extension

### ISSUE THREAD

**Issue by khskarl** [khskarl/gameboy-emulator#7]
It's being created in the project's root path `./gameboy-emulator` instead of the build path `./build/gameboy-emulator`.

Also the executable lacks the `.out` extension, making it harder to ignore it in the .gitignore file.

**Comment by dhustkoder** [comment]
to build the project, you must follow these steps:
$mkdir build
$cd build
$cmake ..
$make

**Comment by khskarl** [comment]
Uh fair enough, my mistake, gonna close the issue then.
